import { PrismaClient } from '@prisma/client';
import { hashPassword } from '@/auth/session';

const prisma = new PrismaClient();

export async function seed() {
    try {
        console.log('🌱 Starting database seed...');

        // Seed regions
        console.log('🗺️ Seeding regions...');
        const regions = [
            { id: 1, name: 'Tanger-Tétouan-Al Hoceïma' },
            { id: 2, name: "l'Oriental" },
            { id: 3, name: 'Fès-Meknès' },
            { id: 4, name: 'Rabat-Salé-Kénitra' },
            { id: 5, name: 'Béni Mellal-Khénifra' },
            { id: 6, name: 'Casablanca-Settat' },
            { id: 7, name: 'Marrakech-Safi' },
            { id: 8, name: 'Drâa-Tafilalet' },
            { id: 9, name: 'Souss-Massa' },
            { id: 10, name: 'Guelmim-Oued Noun' },
            { id: 11, name: 'Laâyoune-Sakia El Hamra' },
            { id: 12, name: 'Dakhla-Oued Ed Dahab' },
        ];

        for (const region of regions) {
            await prisma.region.upsert({
                where: { id: region.id },
                update: {},
                create: region,
            });
        }
        console.log('✅ Regions seeded successfully');

        // Seed cities (exact IDs from SQL script)
        console.log('🏙️ Seeding cities...');
        const cities = [
            { id: 1, name: 'Aïn Harrouda', regionId: 6 },
            { id: 2, name: 'Ben Yakhlef', regionId: 6 },
            { id: 3, name: 'Bouskoura', regionId: 6 },
            { id: 4, name: 'Casablanca', regionId: 6 },
            { id: 5, name: 'Médiouna', regionId: 6 },
            { id: 6, name: 'Mohammadia', regionId: 6 },
            { id: 7, name: 'Tit Mellil', regionId: 6 },
            { id: 9, name: 'Bejaâd', regionId: 5 },
            { id: 10, name: 'Ben Ahmed', regionId: 6 },
            { id: 11, name: 'Benslimane', regionId: 6 },
            { id: 12, name: 'Berrechid', regionId: 6 },
            { id: 13, name: 'Boujniba', regionId: 5 },
            { id: 14, name: 'Boulanouare', regionId: 5 },
            { id: 15, name: 'Bouznika', regionId: 6 },
            { id: 16, name: 'Deroua', regionId: 6 },
            { id: 17, name: 'El Borouj', regionId: 6 },
            { id: 18, name: 'El Gara', regionId: 6 },
            { id: 19, name: 'Guisser', regionId: 6 },
            { id: 20, name: 'Hattane', regionId: 5 },
            { id: 21, name: 'Khouribga', regionId: 5 },
            { id: 22, name: 'Loulad', regionId: 6 },
            { id: 23, name: 'Oued Zem', regionId: 5 },
            { id: 24, name: 'Oulad Abbou', regionId: 6 },
            { id: 25, name: "Oulad H'Riz Sahel", regionId: 6 },
            { id: 26, name: "Oulad M'rah", regionId: 6 },
            { id: 27, name: 'Oulad Saïd', regionId: 6 },
            { id: 28, name: 'Oulad Sidi Ben Daoud', regionId: 6 },
            { id: 29, name: 'Ras El Aïn', regionId: 6 },
            { id: 30, name: 'Settat', regionId: 6 },
            { id: 31, name: 'Sidi Rahhal Chataï', regionId: 6 },
            { id: 32, name: 'Soualem', regionId: 6 },
            { id: 33, name: 'Azemmour', regionId: 6 },
            { id: 34, name: 'Bir Jdid', regionId: 6 },
            { id: 35, name: 'Bouguedra', regionId: 7 },
            { id: 36, name: 'Echemmaia', regionId: 7 },
            { id: 37, name: 'El Jadida', regionId: 6 },
            { id: 38, name: 'Hrara', regionId: 7 },
            { id: 39, name: 'Ighoud', regionId: 7 },
            { id: 40, name: 'Jamâat Shaim', regionId: 7 },
            { id: 41, name: 'Jorf Lasfar', regionId: 6 },
            { id: 42, name: 'Khemis Zemamra', regionId: 6 },
            { id: 43, name: 'Laaounate', regionId: 6 },
            { id: 44, name: 'Moulay Abdallah', regionId: 6 },
            { id: 45, name: 'Oualidia', regionId: 6 },
            { id: 46, name: 'Oulad Amrane', regionId: 6 },
            { id: 47, name: 'Oulad Frej', regionId: 6 },
            { id: 48, name: 'Oulad Ghadbane', regionId: 6 },
            { id: 49, name: 'Safi', regionId: 7 },
            { id: 50, name: 'Sebt El Maârif', regionId: 6 },
            { id: 51, name: 'Sebt Gzoula', regionId: 7 },
            { id: 52, name: 'Sidi Ahmed', regionId: 7 },
            { id: 53, name: 'Sidi Ali Ban Hamdouche', regionId: 6 },
            { id: 54, name: 'Sidi Bennour', regionId: 6 },
            { id: 55, name: 'Sidi Bouzid', regionId: 6 },
            { id: 56, name: 'Sidi Smaïl', regionId: 6 },
            { id: 57, name: 'Youssoufia', regionId: 7 },
            { id: 58, name: 'Fès', regionId: 3 },
            { id: 59, name: 'Aïn Cheggag', regionId: 3 },
            { id: 60, name: 'Bhalil', regionId: 3 },
            { id: 61, name: 'Boulemane', regionId: 3 },
            { id: 62, name: 'El Menzel', regionId: 3 },
            { id: 63, name: 'Guigou', regionId: 3 },
            { id: 64, name: 'Imouzzer Kandar', regionId: 3 },
            { id: 65, name: 'Imouzzer Marmoucha', regionId: 3 },
            { id: 66, name: 'Missour', regionId: 3 },
            { id: 67, name: 'Moulay Yaâcoub', regionId: 3 },
            { id: 68, name: 'Ouled Tayeb', regionId: 3 },
            { id: 69, name: 'Outat El Haj', regionId: 3 },
            { id: 70, name: 'Ribate El Kheir', regionId: 3 },
            { id: 71, name: 'Séfrou', regionId: 3 },
            { id: 72, name: 'Skhinate', regionId: 3 },
            { id: 73, name: 'Tafajight', regionId: 3 },
            { id: 74, name: 'Arbaoua', regionId: 4 },
            { id: 75, name: 'Aïn Dorij', regionId: 1 },
            { id: 76, name: 'Dar Gueddari', regionId: 4 },
            { id: 77, name: 'Had Kourt', regionId: 4 },
            { id: 78, name: 'Jorf El Melha', regionId: 4 },
            { id: 79, name: 'Kénitra', regionId: 4 },
            { id: 80, name: 'Khenichet', regionId: 4 },
            { id: 81, name: 'Lalla Mimouna', regionId: 4 },
            { id: 82, name: 'Mechra Bel Ksiri', regionId: 4 },
            { id: 83, name: 'Mehdia', regionId: 4 },
            { id: 84, name: 'Moulay Bousselham', regionId: 4 },
            { id: 85, name: 'Sidi Allal Tazi', regionId: 4 },
            { id: 86, name: 'Sidi Kacem', regionId: 4 },
            { id: 87, name: 'Sidi Slimane', regionId: 4 },
            { id: 88, name: 'Sidi Taibi', regionId: 4 },
            { id: 89, name: 'Sidi Yahya El Gharb', regionId: 4 },
            { id: 90, name: 'Souk El Arbaa', regionId: 4 },
            { id: 91, name: 'Akka', regionId: 9 },
            { id: 92, name: 'Assa', regionId: 10 },
            { id: 93, name: 'Bouizakarne', regionId: 10 },
            { id: 94, name: 'El Ouatia', regionId: 10 },
            { id: 95, name: 'Es-Semara', regionId: 11 },
            { id: 96, name: 'Fam El Hisn', regionId: 9 },
            { id: 97, name: 'Foum Zguid', regionId: 9 },
            { id: 98, name: 'Guelmim', regionId: 10 },
            { id: 99, name: 'Taghjijt', regionId: 10 },
            { id: 100, name: 'Tan-Tan', regionId: 10 },
            { id: 101, name: 'Tata', regionId: 9 },
            { id: 102, name: 'Zag', regionId: 10 },
            { id: 103, name: 'Marrakech', regionId: 7 },
            { id: 104, name: 'Ait Daoud', regionId: 7 },
            { id: 115, name: 'Amizmiz', regionId: 7 },
            { id: 116, name: 'Assahrij', regionId: 7 },
            { id: 117, name: 'Aït Ourir', regionId: 7 },
            { id: 118, name: 'Ben Guerir', regionId: 7 },
            { id: 119, name: 'Chichaoua', regionId: 7 },
            { id: 120, name: 'El Hanchane', regionId: 7 },
            { id: 121, name: 'El Kelaâ des Sraghna', regionId: 7 },
            { id: 122, name: 'Essaouira', regionId: 7 },
            { id: 123, name: 'Fraïta', regionId: 7 },
            { id: 124, name: 'Ghmate', regionId: 7 },
            { id: 125, name: 'Ighounane', regionId: 8 },
            { id: 126, name: 'Imintanoute', regionId: 7 },
            { id: 127, name: 'Kattara', regionId: 7 },
            { id: 128, name: 'Lalla Takerkoust', regionId: 7 },
            { id: 129, name: 'Loudaya', regionId: 7 },
            { id: 130, name: 'Lâattaouia', regionId: 7 },
            { id: 131, name: 'Moulay Brahim', regionId: 7 },
            { id: 132, name: 'Mzouda', regionId: 7 },
            { id: 133, name: 'Ounagha', regionId: 7 },
            { id: 134, name: "Sid L'Mokhtar", regionId: 7 },
            { id: 135, name: 'Sid Zouin', regionId: 7 },
            { id: 136, name: 'Sidi Abdallah Ghiat', regionId: 7 },
            { id: 137, name: 'Sidi Bou Othmane', regionId: 7 },
            { id: 138, name: 'Sidi Rahhal', regionId: 7 },
            { id: 139, name: 'Skhour Rehamna', regionId: 7 },
            { id: 140, name: 'Smimou', regionId: 7 },
            { id: 141, name: 'Tafetachte', regionId: 7 },
            { id: 142, name: 'Tahannaout', regionId: 7 },
            { id: 143, name: 'Talmest', regionId: 7 },
            { id: 144, name: 'Tamallalt', regionId: 7 },
            { id: 145, name: 'Tamanar', regionId: 7 },
            { id: 146, name: 'Tamansourt', regionId: 7 },
            { id: 147, name: 'Tameslouht', regionId: 7 },
            { id: 148, name: 'Tanalt', regionId: 9 },
            { id: 150, name: 'Meknès', regionId: 3 },
            { id: 151, name: 'Khénifra', regionId: 5 },
            { id: 152, name: 'Agourai', regionId: 3 },
            { id: 153, name: 'Ain Taoujdate', regionId: 3 },
            { id: 154, name: 'MyAliCherif', regionId: 8 },
            { id: 155, name: 'Rissani', regionId: 8 },
            { id: 156, name: 'Amalou Ighriben', regionId: 5 },
            { id: 157, name: 'Aoufous', regionId: 8 },
            { id: 158, name: 'Arfoud', regionId: 8 },
            { id: 159, name: 'Azrou', regionId: 3 },
            { id: 160, name: 'Aïn Jemaa', regionId: 3 },
            { id: 161, name: 'Aïn Karma', regionId: 3 },
            { id: 162, name: 'Aïn Leuh', regionId: 3 },
            { id: 163, name: 'Aït Boubidmane', regionId: 3 },
            { id: 164, name: 'Aït Ishaq', regionId: 5 },
            { id: 165, name: 'Boudnib', regionId: 8 },
            { id: 166, name: 'Boufakrane', regionId: 3 },
            { id: 167, name: 'Boumia', regionId: 8 },
            { id: 168, name: 'El Hajeb', regionId: 3 },
            { id: 169, name: 'Elkbab', regionId: 5 },
            { id: 170, name: 'Er-Rich', regionId: 5 },
            { id: 171, name: 'Errachidia', regionId: 8 },
            { id: 172, name: 'Gardmit', regionId: 8 },
            { id: 173, name: 'Goulmima', regionId: 8 },
            { id: 174, name: 'Gourrama', regionId: 8 },
            { id: 175, name: 'Had Bouhssoussen', regionId: 5 },
            { id: 176, name: 'Haj Kaddour', regionId: 3 },
            { id: 177, name: 'Ifrane', regionId: 3 },
            { id: 178, name: 'Itzer', regionId: 8 },
            { id: 179, name: 'Jorf', regionId: 8 },
            { id: 180, name: 'Kehf Nsour', regionId: 5 },
            { id: 181, name: 'Kerrouchen', regionId: 5 },
            { id: 182, name: "M'haya", regionId: 3 },
            { id: 183, name: "M'rirt", regionId: 5 },
            { id: 184, name: 'Midelt', regionId: 8 },
            { id: 185, name: 'Moulay Ali Cherif', regionId: 8 },
            { id: 186, name: 'Moulay Bouazza', regionId: 5 },
            { id: 187, name: 'Moulay Idriss Zerhoun', regionId: 3 },
            { id: 188, name: 'Moussaoua', regionId: 3 },
            { id: 189, name: "N'Zalat Bni Amar", regionId: 3 },
            { id: 190, name: 'Ouaoumana', regionId: 5 },
            { id: 191, name: 'Oued Ifrane', regionId: 3 },
            { id: 192, name: 'Sabaa Aiyoun', regionId: 3 },
            { id: 193, name: 'Sebt Jahjouh', regionId: 3 },
            { id: 194, name: 'Sidi Addi', regionId: 3 },
            { id: 195, name: 'Tichoute', regionId: 8 },
            { id: 196, name: 'Tighassaline', regionId: 5 },
            { id: 197, name: 'Tighza', regionId: 5 },
            { id: 198, name: 'Timahdite', regionId: 3 },
            { id: 199, name: 'Tinejdad', regionId: 8 },
            { id: 200, name: 'Tizguite', regionId: 3 },
            { id: 201, name: 'Toulal', regionId: 3 },
            { id: 202, name: 'Tounfite', regionId: 8 },
            { id: 203, name: "Zaouia d'Ifrane", regionId: 3 },
            { id: 204, name: 'Zaïda', regionId: 8 },
            { id: 205, name: 'Ahfir', regionId: 2 },
            { id: 206, name: 'Aklim', regionId: 2 },
            { id: 207, name: 'Al Aroui', regionId: 2 },
            { id: 208, name: 'Aïn Bni Mathar', regionId: 2 },
            { id: 209, name: 'Aïn Erreggada', regionId: 2 },
            { id: 210, name: 'Ben Taïeb', regionId: 2 },
            { id: 211, name: 'Berkane', regionId: 2 },
            { id: 212, name: 'Bni Ansar', regionId: 2 },
            { id: 213, name: 'Bni Chiker', regionId: 2 },
            { id: 214, name: 'Bni Drar', regionId: 2 },
            { id: 215, name: 'Bni Tadjite', regionId: 2 },
            { id: 216, name: 'Bouanane', regionId: 2 },
            { id: 217, name: 'Bouarfa', regionId: 2 },
            { id: 218, name: 'Bouhdila', regionId: 2 },
            { id: 219, name: 'Dar El Kebdani', regionId: 2 },
            { id: 220, name: 'Debdou', regionId: 2 },
            { id: 221, name: 'Douar Kannine', regionId: 2 },
            { id: 222, name: 'Driouch', regionId: 2 },
            { id: 223, name: 'El Aïoun Sidi Mellouk', regionId: 2 },
            { id: 224, name: 'Farkhana', regionId: 2 },
            { id: 225, name: 'Figuig', regionId: 2 },
            { id: 226, name: 'Ihddaden', regionId: 2 },
            { id: 227, name: 'Jaâdar', regionId: 2 },
            { id: 228, name: 'Jerada', regionId: 2 },
            { id: 229, name: 'Kariat Arekmane', regionId: 2 },
            { id: 230, name: 'Kassita', regionId: 2 },
            { id: 231, name: 'Kerouna', regionId: 2 },
            { id: 232, name: 'Laâtamna', regionId: 2 },
            { id: 233, name: 'Madagh', regionId: 2 },
            { id: 234, name: 'Midar', regionId: 2 },
            { id: 235, name: 'Nador', regionId: 2 },
            { id: 236, name: 'Naima', regionId: 2 },
            { id: 237, name: 'Oued Heimer', regionId: 2 },
            { id: 238, name: 'Oujda', regionId: 2 },
            { id: 239, name: 'Ras El Ma', regionId: 2 },
            { id: 240, name: 'Saïdia', regionId: 2 },
            { id: 241, name: 'Selouane', regionId: 2 },
            { id: 242, name: 'Sidi Boubker', regionId: 2 },
            { id: 243, name: 'Sidi Slimane Echcharaa', regionId: 2 },
            { id: 244, name: 'Talsint', regionId: 2 },
            { id: 245, name: 'Taourirt', regionId: 2 },
            { id: 246, name: 'Tendrara', regionId: 2 },
            { id: 247, name: 'Tiztoutine', regionId: 2 },
            { id: 248, name: 'Touima', regionId: 2 },
            { id: 249, name: 'Touissit', regionId: 2 },
            { id: 250, name: 'Zaïo', regionId: 2 },
            { id: 251, name: 'Zeghanghane', regionId: 2 },
            { id: 252, name: 'Rabat', regionId: 4 },
            { id: 253, name: 'Salé', regionId: 4 },
            { id: 254, name: 'Ain El Aouda', regionId: 4 },
            { id: 255, name: 'Harhoura', regionId: 4 },
            { id: 256, name: 'Khémisset', regionId: 4 },
            { id: 257, name: 'Oulmès', regionId: 4 },
            { id: 258, name: 'Rommani', regionId: 4 },
            { id: 259, name: 'Sidi Allal El Bahraoui', regionId: 4 },
            { id: 260, name: 'Sidi Bouknadel', regionId: 4 },
            { id: 261, name: 'Skhirate', regionId: 4 },
            { id: 262, name: 'Tamesna', regionId: 4 },
            { id: 263, name: 'Témara', regionId: 4 },
            { id: 264, name: 'Tiddas', regionId: 4 },
            { id: 265, name: 'Tiflet', regionId: 4 },
            { id: 266, name: 'Touarga', regionId: 4 },
            { id: 267, name: 'Agadir', regionId: 9 },
            { id: 268, name: 'Agdz', regionId: 8 },
            { id: 269, name: 'Agni Izimmer', regionId: 9 },
            { id: 270, name: 'Aït Melloul', regionId: 9 },
            { id: 271, name: 'Alnif', regionId: 8 },
            { id: 272, name: 'Anzi', regionId: 9 },
            { id: 273, name: 'Aoulouz', regionId: 9 },
            { id: 274, name: 'Aourir', regionId: 9 },
            { id: 275, name: 'Arazane', regionId: 9 },
            { id: 276, name: 'Aït Baha', regionId: 9 },
            { id: 277, name: 'Aït Iaâza', regionId: 9 },
            { id: 278, name: 'Aït Yalla', regionId: 8 },
            { id: 279, name: 'Ben Sergao', regionId: 9 },
            { id: 280, name: 'Biougra', regionId: 9 },
            { id: 281, name: 'Boumalne-Dadès', regionId: 8 },
            { id: 282, name: 'Dcheira El Jihadia', regionId: 9 },
            { id: 283, name: 'Drargua', regionId: 9 },
            { id: 284, name: 'El Guerdane', regionId: 9 },
            { id: 285, name: 'Harte Lyamine', regionId: 8 },
            { id: 286, name: 'Ida Ougnidif', regionId: 9 },
            { id: 287, name: 'Ifri', regionId: 8 },
            { id: 288, name: 'Igdamen', regionId: 9 },
            { id: 289, name: "Ighil n'Oumgoun", regionId: 8 },
            { id: 290, name: 'Imassine', regionId: 8 },
            { id: 291, name: 'Inezgane', regionId: 9 },
            { id: 292, name: 'Irherm', regionId: 9 },
            { id: 293, name: "Kelaat-M'Gouna", regionId: 8 },
            { id: 294, name: 'Lakhsas', regionId: 9 },
            { id: 295, name: 'Lakhsass', regionId: 9 },
            { id: 296, name: 'Lqliâa', regionId: 9 },
            { id: 297, name: "M'semrir", regionId: 8 },
            { id: 298, name: 'Massa (Maroc)', regionId: 9 },
            { id: 299, name: 'Megousse', regionId: 9 },
            { id: 300, name: 'Ouarzazate', regionId: 8 },
            { id: 301, name: 'Oulad Berhil', regionId: 9 },
            { id: 302, name: 'Oulad Teïma', regionId: 9 },
            { id: 303, name: 'Sarghine', regionId: 8 },
            { id: 304, name: 'Sidi Ifni', regionId: 10 },
            { id: 305, name: 'Skoura', regionId: 8 },
            { id: 306, name: 'Tabounte', regionId: 8 },
            { id: 307, name: 'Tafraout', regionId: 9 },
            { id: 308, name: 'Taghzout', regionId: 1 },
            { id: 309, name: 'Tagzen', regionId: 9 },
            { id: 310, name: 'Taliouine', regionId: 9 },
            { id: 311, name: 'Tamegroute', regionId: 8 },
            { id: 312, name: 'Tamraght', regionId: 9 },
            { id: 313, name: 'Tanoumrite Nkob Zagora', regionId: 8 },
            { id: 314, name: 'Taourirt ait zaghar', regionId: 8 },
            { id: 315, name: 'Taroudannt', regionId: 9 },
            { id: 316, name: 'Temsia', regionId: 9 },
            { id: 317, name: 'Tifnit', regionId: 9 },
            { id: 318, name: 'Tisgdal', regionId: 9 },
            { id: 319, name: 'Tiznit', regionId: 9 },
            { id: 320, name: 'Toundoute', regionId: 8 },
            { id: 321, name: 'Zagora', regionId: 8 },
            { id: 322, name: 'Afourar', regionId: 5 },
            { id: 323, name: 'Aghbala', regionId: 5 },
            { id: 324, name: 'Azilal', regionId: 5 },
            { id: 325, name: 'Aït Majden', regionId: 5 },
            { id: 326, name: 'Beni Ayat', regionId: 5 },
            { id: 327, name: 'Béni Mellal', regionId: 5 },
            { id: 328, name: 'Bin elouidane', regionId: 5 },
            { id: 329, name: 'Bradia', regionId: 5 },
            { id: 330, name: 'Bzou', regionId: 5 },
            { id: 331, name: 'Dar Oulad Zidouh', regionId: 5 },
            { id: 332, name: 'Demnate', regionId: 5 },
            { id: 333, name: "Dra'a", regionId: 8 },
            { id: 334, name: 'El Ksiba', regionId: 5 },
            { id: 335, name: 'Foum Jamaa', regionId: 5 },
            { id: 336, name: 'Fquih Ben Salah', regionId: 5 },
            { id: 337, name: 'Kasba Tadla', regionId: 5 },
            { id: 338, name: 'Ouaouizeght', regionId: 5 },
            { id: 339, name: 'Oulad Ayad', regionId: 5 },
            { id: 340, name: "Oulad M'Barek", regionId: 5 },
            { id: 341, name: 'Oulad Yaich', regionId: 5 },
            { id: 342, name: 'Sidi Jaber', regionId: 5 },
            { id: 343, name: 'Souk Sebt Oulad Nemma', regionId: 5 },
            { id: 344, name: 'Zaouïat Cheikh', regionId: 5 },
            { id: 345, name: 'Tanger', regionId: 1 },
            { id: 346, name: 'Tétouan', regionId: 1 },
            { id: 347, name: 'Akchour', regionId: 1 },
            { id: 348, name: 'Assilah', regionId: 1 },
            { id: 349, name: 'Bab Berred', regionId: 1 },
            { id: 350, name: 'Bab Taza', regionId: 1 },
            { id: 351, name: 'Brikcha', regionId: 1 },
            { id: 352, name: 'Chefchaouen', regionId: 1 },
            { id: 353, name: 'Dar Bni Karrich', regionId: 1 },
            { id: 354, name: 'Dar Chaoui', regionId: 1 },
            { id: 355, name: 'Fnideq', regionId: 1 },
            { id: 356, name: 'Gueznaia', regionId: 1 },
            { id: 357, name: 'Jebha', regionId: 1 },
            { id: 358, name: 'Karia', regionId: 3 },
            { id: 359, name: 'Khémis Sahel', regionId: 1 },
            { id: 360, name: 'Ksar El Kébir', regionId: 1 },
            { id: 361, name: 'Larache', regionId: 1 },
            { id: 362, name: "M'diq", regionId: 1 },
            { id: 363, name: 'Martil', regionId: 1 },
            { id: 364, name: 'Moqrisset', regionId: 1 },
            { id: 365, name: 'Oued Laou', regionId: 1 },
            { id: 366, name: 'Oued Rmel', regionId: 1 },
            { id: 367, name: 'Ouazzane', regionId: 1 },
            { id: 368, name: 'Point Cires', regionId: 1 },
            { id: 369, name: 'Sidi Lyamani', regionId: 1 },
            {
                id: 370,
                name: 'Sidi Mohamed ben Abdallah el-Raisuni',
                regionId: 1,
            },
            { id: 371, name: 'Zinat', regionId: 1 },
            { id: 372, name: 'Ajdir', regionId: 1 },
            { id: 373, name: 'Aknoul', regionId: 3 },
            { id: 374, name: 'Al Hoceïma', regionId: 1 },
            { id: 375, name: 'Aït Hichem', regionId: 1 },
            { id: 376, name: 'Bni Bouayach', regionId: 1 },
            { id: 377, name: 'Bni Hadifa', regionId: 1 },
            { id: 378, name: 'Ghafsai', regionId: 3 },
            { id: 379, name: 'Guercif', regionId: 2 },
            { id: 380, name: 'Imzouren', regionId: 1 },
            { id: 381, name: 'Inahnahen', regionId: 1 },
            { id: 382, name: 'Issaguen (Ketama)', regionId: 1 },
            { id: 383, name: 'Karia (El Jadida)', regionId: 6 },
            { id: 384, name: 'Karia Ba Mohamed', regionId: 3 },
            { id: 385, name: 'Oued Amlil', regionId: 3 },
            { id: 386, name: 'Oulad Zbair', regionId: 3 },
            { id: 387, name: 'Tahla', regionId: 3 },
            { id: 388, name: 'Tala Tazegwaght', regionId: 1 },
            { id: 389, name: 'Tamassint', regionId: 1 },
            { id: 390, name: 'Taounate', regionId: 3 },
            { id: 391, name: 'Targuist', regionId: 1 },
            { id: 392, name: 'Taza', regionId: 3 },
            { id: 393, name: 'Taïnaste', regionId: 3 },
            { id: 394, name: 'Thar Es-Souk', regionId: 3 },
            { id: 395, name: 'Tissa', regionId: 3 },
            { id: 396, name: 'Tizi Ouasli', regionId: 3 },
            { id: 397, name: 'Laayoune', regionId: 11 },
            { id: 398, name: 'El Marsa', regionId: 11 },
            { id: 399, name: 'Tarfaya', regionId: 11 },
            { id: 400, name: 'Boujdour', regionId: 11 },
            { id: 401, name: 'Awsard', regionId: 12 },
            { id: 402, name: 'Oued-Eddahab', regionId: 12 },
            { id: 403, name: 'Stehat', regionId: 1 },
            { id: 404, name: 'Aït Attab', regionId: 5 },
        ];

        for (const city of cities) {
            await prisma.city.upsert({
                where: { id: city.id },
                update: {},
                create: city,
            });
        }
        console.log('✅ Cities seeded successfully');

        // Create admin user
        const adminEmail = 'admin@example.com';

        const existingAdmin = await prisma.user.findUnique({
            where: { email: adminEmail },
        });

        if (!existingAdmin) {
            const passwordHash = await hashPassword('admin123');

            const admin = await prisma.user.create({
                data: {
                    email: adminEmail,
                    passwordHash,
                    role: 'ADMIN',
                    name: 'Admin User',
                    bloodGroup: 'A_POSITIVE',
                },
            });

            // Create initial activity log
            await prisma.activityLog.create({
                data: {
                    userId: admin.id,
                    action: 'SIGN_UP',
                    ipAddress: '127.0.0.1',
                },
            });

            console.log('👤 Created admin user:', {
                email: admin.email,
                role: admin.role,
            });
        } else {
            console.log('👤 Admin user already exists, skipping...');
        }

        console.log('✅ Seed completed successfully');
    } catch (error) {
        console.error('❌ Seed error:', error);
        throw error;
    }
}

seed()
    .catch(error => {
        console.error('❌ Seed failed:', error);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
